export const RANDOM_NAMES = [
  "Jane Smith",
  "Michael Johnson",
  "Emily Williams",
  "David Brown",
  "Sarah Davis",
  "Robert Wilson",
  "Jennifer Jones",
  "William Taylor",
  "Linda Martinez",
  "James Anderson",
  "Mary Johnson",
  "Richard Wilson",
  "Patricia Moore",
  "Thomas Lee",
  "Nancy White",
  "Charles Turner",
  "Linda Harris",
  "Daniel Adams",
  "Susan Walker",
  "Matthew Allen",
  "Karen Nelson",
  "Joseph Mitchell",
  "Lisa Hall",
  "Christopher Lopez",
  "Betty Clark",
  "Daniel Lewis",
  "Margaret King",
  "Anthony White",
  "Dorothy Carter",
  "Kwame Appiah",
  "Amina Nwokolo",
  "Moussa Diop",
  "Fatoumata Keita",
  "Lwazi Ndlovu",
  "Ayo Adeyemi",
  "Nadia Kamara",
  "Tariq Abubakar",
  "Chinwe Onyeka",
  "Sekou Toure",
  "Carlos Silva",
  "Ana Santos",
  "Rafael Pereira",
  "Mariana Oliveira",
  "André Costa",
  "Luana Almeida",
  "Paulo Gomes",
  "Isabela Fernandes",
  "Fernando Rodrigues",
  "Juliana Souza",
  "Felipe Medeiros",
];

export const RANDOM_COUNTRIES = [
  "United States",
  "Canada",
  "United Kingdom",
  "France",
  "Germany",
  "Australia",
  "Brazil",
  "Mexico",
  "Spain",
  "Italy",
  "Argentina",
  "Sweden",
  "Greece",
  "Saudi Arabia",
  "Canada",
  "Switzerland",
  "Chile",
  "Norway",
  "Ireland",
  "New Zealand",
];

export const METHODS = ["deposit", "withdrawal", "sent", "received"];
