export interface IconProps {
  color: string;
  size: number;
}

export enum Icons {
  AddSquare = "add-Square",
  AlertCircle = "alert-circle",
  ArrowLeft = "arrow-left",
  ArrowRight = "arrow-right",
  Attachment = "attachment",
  Bin = "bin",
  Calendar = "calendar",
  Call = "call",
  Calling = "calling",
  CallMissed = "call-missed",
  Cancel = "cancel",
  Chat = "chat",
  Check = "check",
  ChevronDown = "chevron-down",
  ChevronUp = "chevron-up",
  Clock = "clock",
  Close = "close",
  DangerCircle = "danger-circle",
  DangerTriangle = "danger-triangle",
  DocFile = "doc-file",
  DocumentAlignRight = "document-align-right",
  DocumentUpload = "document-upload",
  Dot = "dot",
  EditSquare = "edit-square",
  Ellipse = "ellipse",
  Email = "email",
  ExpandFill = "expand-fill",
  EyeClose = "eye-close",
  EyeOpen = "eye-open",
  Facebook = "facebook",
  FaqCircle = "faq-circle",
  Filter = "filter",
  GmailColored = "gmail-colored",
  Hamburger = "hamburger",
  HiIcon = "hiicon",
  Home = "home",
  Image = "image",
  InfoSquare = "info-square",
  Instagram = "instagram",
  Linkedin = "linkedin",
  Location = "location",
  LogOut = "log-out",
  Medium = "medium",
  Message = "message",
  MicMute = "mic-mute",
  More = "more",
  Notification = "notification",
  PdfFile = "pdf-file",
  Play = "play",
  ProfileCircle = "profile-circle",
  Search = "search",
  SearchLens = "searchLens",
  Setting = "setting",
  TableBin = "tableBin",
  Tag = "tag",
  Telephone = "telephone",
  TickSquare = "tick-square",
  TimeCircle = "time",
  Twitter = "twitter",
  User = "user",
  Whatsapp = "whatsapp",
  WhatsappGreen = "whatsapp-green",
}
